include:
  - bccvl.pki
  - bccvl.rsyslog
  - bccvl.rabbitmq
  - bccvl.apache
  - bccvl.4store
  - bccvl.varnish
  - bccvl.haproxy
  - bccvl.data_mover
  - bccvl.data_mover_worker
  - bccvl.visualiser
  - bccvl.plone
